name: Android CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Distribute
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant Execute Permission to Gradlew
        run: chmod +x ./gradlew

      - name: Increment Version Code
        run: |
          VERSION_CODE=$(grep VERSION_CODE version.properties | cut -d'=' -f2)
          NEW_VERSION_CODE=$((VERSION_CODE + 1))
          sed -i "s/VERSION_CODE=$VERSION_CODE/VERSION_CODE=$NEW_VERSION_CODE/" version.properties
          echo "Updated VERSION_CODE to $NEW_VERSION_CODE"
          
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: app/build/outputs/apk/debug/app-debug.apk
          groups: testers
